[project]
name = "whatapp-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [emoji==2.14.1
matplotlib==3.10.5
pandas==2.3.2
seaborn==0.13.2
streamlit==1.48.1
urlextract==1.9.0
wordcloud==1.9.4
]
